import { CONCEPTS_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const conceptsNavigationConfig: NavigationTree[] = [
    // ─── GMAO ────────────────────────────────────────────────────────
    {
        key: 'gmao',
        path: '',
        title: 'GMAO',
        translateKey: 'nav.gmao',
        icon: 'concepts',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['assets.read', 'work_orders.read', 'inventory.read', 'pm_plans.read', 'purchasing.read', 'admin', 'manager', 'technician'],
        subMenu: [
            // Assets
            {
                key: 'concepts.assets',
                path: '',
                title: 'Assets',
                translateKey: 'nav.assets.assets',
                icon: 'assets',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['assets.read', 'admin', 'manager', 'technician'],
                subMenu: [
                    {
                        key: 'concepts.assets.assetList',
                        path: `${CONCEPTS_PREFIX_PATH}/assets/asset-list`,
                        title: 'Asset List',
                        translateKey: 'nav.assets.assetList',
                        icon: 'assetList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['assets.read', 'admin', 'manager', 'technician'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.assets.assetCreate',
                        path: `${CONCEPTS_PREFIX_PATH}/assets/asset-create`,
                        title: 'Add Asset',
                        translateKey: 'nav.assets.assetCreate',
                        icon: 'assetCreate',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['assets.write', 'admin', 'manager'],
                        subMenu: [],
                    },
                ],
            },

            // Work Orders
            {
                key: 'concepts.workOrders',
                path: '',
                title: 'Work Orders',
                translateKey: 'nav.workOrders.workOrders',
                icon: 'workOrders',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['work_orders.read', 'admin', 'manager', 'technician'],
                subMenu: [
                    {
                        key: 'concepts.workOrders.workOrderList',
                        path: `${CONCEPTS_PREFIX_PATH}/work-orders/work-order-list`,
                        title: 'Work Order List',
                        translateKey: 'nav.workOrders.workOrderList',
                        icon: 'workOrderList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['work_orders.read', 'admin', 'manager', 'technician'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.workOrders.workOrderBoard',
                        path: `${CONCEPTS_PREFIX_PATH}/work-orders/work-order-board`,
                        title: 'Board',
                        translateKey: 'nav.workOrders.workOrderBoard',
                        icon: 'workOrderBoard',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['work_orders.read', 'admin', 'manager', 'technician'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.workOrders.workOrderCreate',
                        path: `${CONCEPTS_PREFIX_PATH}/work-orders/work-order-create`,
                        title: 'New Work Order',
                        translateKey: 'nav.workOrders.workOrderCreate',
                        icon: 'workOrderCreate',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['work_orders.write', 'admin', 'manager', 'technician'],
                        subMenu: [],
                    },
                ],
            },

            // Preventive Maintenance
            {
                key: 'concepts.pm',
                path: '',
                title: 'Preventive Maintenance',
                translateKey: 'nav.pm.pm',
                icon: 'pm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['pm_plans.read', 'admin', 'manager'],
                subMenu: [
                    {
                        key: 'concepts.pm.pmList',
                        path: `${CONCEPTS_PREFIX_PATH}/pm/pm-list`,
                        title: 'PM Plans',
                        translateKey: 'nav.pm.pmList',
                        icon: 'pmList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['pm_plans.read', 'admin', 'manager'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.pm.pmCreate',
                        path: `${CONCEPTS_PREFIX_PATH}/pm/pm-create`,
                        title: 'New PM Plan',
                        translateKey: 'nav.pm.pmCreate',
                        icon: 'pmCreate',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['pm_plans.write', 'admin', 'manager'],
                        subMenu: [],
                    },
                ],
            },

            // Inventory
            {
                key: 'concepts.inventory',
                path: '',
                title: 'Inventory',
                translateKey: 'nav.inventory.inventory',
                icon: 'inventory',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['inventory.read', 'admin', 'manager', 'technician'],
                subMenu: [
                    {
                        key: 'concepts.inventory.items',
                        path: `${CONCEPTS_PREFIX_PATH}/inventory/items`,
                        title: 'Items',
                        translateKey: 'nav.inventory.items',
                        icon: 'inventoryItems',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['inventory.read', 'admin', 'manager', 'technician'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.inventory.warehouses',
                        path: `${CONCEPTS_PREFIX_PATH}/inventory/warehouses`,
                        title: 'Warehouses',
                        translateKey: 'nav.inventory.warehouses',
                        icon: 'inventoryWarehouses',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['inventory.write', 'admin', 'manager'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.inventory.stockMoves',
                        path: `${CONCEPTS_PREFIX_PATH}/inventory/stock-moves`,
                        title: 'Stock Moves',
                        translateKey: 'nav.inventory.stockMoves',
                        icon: 'inventoryStockMoves',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['inventory.write', 'admin', 'manager'],
                        subMenu: [],
                    },
                ],
            },

            // Purchasing
            {
                key: 'concepts.purchasing',
                path: '',
                title: 'Purchasing',
                translateKey: 'nav.purchasing.purchasing',
                icon: 'purchasing',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['purchasing.read', 'admin', 'manager'],
                subMenu: [
                    {
                        key: 'concepts.purchasing.suppliers',
                        path: `${CONCEPTS_PREFIX_PATH}/purchasing/suppliers`,
                        title: 'Suppliers',
                        translateKey: 'nav.purchasing.suppliers',
                        icon: 'purchasingSuppliers',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['purchasing.write', 'admin', 'manager'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.purchasing.purchaseOrders',
                        path: `${CONCEPTS_PREFIX_PATH}/purchasing/purchase-orders`,
                        title: 'Purchase Orders',
                        translateKey: 'nav.purchasing.purchaseOrders',
                        icon: 'purchasingOrders',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['purchasing.read', 'admin', 'manager'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.purchasing.receipts',
                        path: `${CONCEPTS_PREFIX_PATH}/purchasing/receipts`,
                        title: 'Receipts',
                        translateKey: 'nav.purchasing.receipts',
                        icon: 'purchasingReceipts',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['purchasing.read', 'admin', 'manager'],
                        subMenu: [],
                    },
                ],
            },

        ],
    },

    // ─── PEOPLE ──────────────────────────────────────────────────────────────
    {
        key: 'people',
        path: '',
        title: 'People',
        translateKey: 'nav.people',
        icon: 'customers',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['members.read', 'departments.read', 'roles.read', 'admin', 'manager', 'hr'],
        subMenu: [
            // Members
            {
                key: 'concepts.members',
                path: '',
                title: 'Members',
                translateKey: 'nav.members.members',
                icon: 'members',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['members.read', 'admin', 'manager', 'hr'],
                subMenu: [
                    {
                        key: 'concepts.customers.customerList',
                        path: `${CONCEPTS_PREFIX_PATH}/customers/customer-list`,
                        title: 'Member List',
                        translateKey: 'nav.members.memberList',
                        icon: 'memberList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['members.read', 'admin', 'manager', 'hr'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.customers.customerCreate',
                        path: `${CONCEPTS_PREFIX_PATH}/customers/customer-create`,
                        title: 'Add Member',
                        translateKey: 'nav.members.memberCreate',
                        icon: 'memberCreate',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['members.create', 'admin', 'hr'],
                        subMenu: [],
                    },
                ],
            },

            // Sites
            {
                key: 'concepts.sites',
                path: '',
                title: 'Sites',
                translateKey: 'nav.sites.sites',
                icon: 'sites',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['sites.read', 'admin'],
                subMenu: [
                    {
                        key: 'concepts.sites.siteList',
                        path: `${CONCEPTS_PREFIX_PATH}/sites`,
                        title: 'Site List',
                        translateKey: 'nav.sites.siteList',
                        icon: 'memberList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['sites.read', 'admin'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.sites.siteCreate',
                        path: `${CONCEPTS_PREFIX_PATH}/sites/site-create`,
                        title: 'Add Site',
                        translateKey: 'nav.sites.siteCreate',
                        icon: 'memberCreate',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['sites.create', 'admin'],
                        subMenu: [],
                    },
                ],
            },

            // Departments
            {
                key: 'concepts.departments',
                path: '',
                title: 'Departments',
                translateKey: 'nav.departments.departments',
                icon: 'departments',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['departments.read', 'admin', 'hr'],
                subMenu: [
                    {
                        key: 'concepts.departments.departmentList',
                        path: `${CONCEPTS_PREFIX_PATH}/departments`,
                        title: 'Department List',
                        translateKey: 'nav.departments.departmentList',
                        icon: 'memberList',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['departments.read', 'admin', 'hr'],
                        subMenu: [],
                    },
                    {
                        key: 'concepts.departments.departmentCreate',
                        path: `${CONCEPTS_PREFIX_PATH}/departments/department-create`,
                        title: 'Add Department',
                        translateKey: 'nav.departments.departmentCreate',
                        icon: 'memberCreate',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: ['departments.create', 'admin', 'hr'],
                        subMenu: [],
                    },
                ],
            },

            // Roles & Permissions
            {
                key: 'concepts.rolesPermissions',
                path: `${CONCEPTS_PREFIX_PATH}/roles-permissions`,
                title: 'Roles & Permissions',
                translateKey: 'nav.rolesPermissions',
                icon: 'rolesPermissions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['roles.read', 'admin'],
                subMenu: [],
            },
        ],
    },

    // ─── WORKSPACE ───────────────────────────────────────────────────────────
    {
        key: 'workspace',
        path: '',
        title: 'Workspace',
        translateKey: 'nav.workspace',
        icon: 'fileManager',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['user'],
        subMenu: [
            {
                key: 'concepts.calendar',
                path: `${CONCEPTS_PREFIX_PATH}/calendar`,
                title: 'Calendar',
                translateKey: 'nav.calendar',
                icon: 'calendar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'concepts.fileManager',
                path: `${CONCEPTS_PREFIX_PATH}/file-manager`,
                title: 'File Manager',
                translateKey: 'nav.fileManager',
                icon: 'fileManager',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['files.read', 'admin', 'manager', 'technician'],
                subMenu: [],
            },
            {
                key: 'concepts.chat',
                path: `${CONCEPTS_PREFIX_PATH}/chat`,
                title: 'Chat',
                translateKey: 'nav.chat',
                icon: 'chat',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'concepts.mail',
                path: `${CONCEPTS_PREFIX_PATH}/mail`,
                title: 'Notifications',
                translateKey: 'nav.notifications',
                icon: 'notifications',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },

    // ─── ACCOUNT ─────────────────────────────────────────────────────────────
    {
        key: 'account',
        path: '',
        title: 'Account',
        translateKey: 'nav.account.account',
        icon: 'account',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['user'],
        subMenu: [
            {
                key: 'concepts.account.settings',
                path: `${CONCEPTS_PREFIX_PATH}/account/settings`,
                title: 'Settings',
                translateKey: 'nav.account.settings',
                icon: 'accountSettings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },
]

export default conceptsNavigationConfig
